# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generates the code changes that correspond to changes in generation_config.yaml.
# A pull request is also created with these changes
name: Hermetic library generation upon generation config change through pull requests
on:
  pull_request:
  workflow_dispatch:
jobs:
  update-googleapis-commit:
    uses: googleapis/sdk-platform-java/.github/workflows/hermetic_library_generation.yaml@centralized-hermetic-workflows

